import { useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle, Circuitry, Database, FileText, FlowArrow, Gear, GridFour, ListMagnifyingGlass, MagnifyingGlass, Play, PuzzlePiece, Pulse, RocketLaunch, ShieldCheck, SquaresFour, Stop, Warning, Waveform, Wrench } from "@phosphor-icons/react";

const stages=[["01","Назначение","изделие и методика"],["02","Готовность","тракт и оборудование"],["03","Калибровка","адреса 97 / 99"],["04","Каналы ЯЛК","0 / 3,1 / 6,2 В"],["05","ЯТП · 0 Ω","30 каналов"],["06","ЯТП · 120 Ω","диалог Р4831"],["07","ЯТП · 240 Ω","30 каналов"],["08","Итог","сброс и отчёт"]];
const modules=[["ubsi","УБСИ","ЯЛК-96 · ЯТП",Waveform],["bsi","БСИ","блоки и параметры",Circuitry],["cells","Отдельные ячейки","по типу и номеру",GridFour],["intermediate","Промежуточные измерения","ручные и приборные",Pulse]];

function Status({tone="ok",children}){const Icon=tone==="ok"?CheckCircle:tone==="warn"?Warning:Stop;return <span className={`status ${tone}`}><Icon weight="fill"/>{children}</span>}
function TopBar({title,subtitle,mode="test",onBack,onEngineering}){return <header className="topbar"><div className="brand-lockup"><img src="/miltech-mark.png" alt="МилТех"/><div><b>МИЛТЕХ СТАНЦИЯ</b><small>{title}</small></div></div><div className="top-context"><span>{subtitle}</span><Status>СТЕНД ГОТОВ</Status><span>БД: ЛОКАЛЬНАЯ</span></div><div className="top-actions">{onBack&&<button className="key-button" onClick={onBack}><ArrowLeft/> НАЗАД</button>}{onEngineering&&<button className="key-button" onClick={onEngineering}><Wrench/> {mode==="test"?"ИНЖЕНЕРНЫЙ ПУЛЬТ":"ИСПЫТАТЕЛЬНЫЙ РЕЖИМ"}</button>}</div></header>}
function Button({children,primary,danger,onClick,disabled}){return <button disabled={disabled} onClick={onClick} className={`command ${primary?"primary":""} ${danger?"danger":""}`}>{children}</button>}
function Panel({title,badge,children,className=""}){return <section className={`panel ${className}`}><div className="panel-title"><h2>{title}</h2>{badge}</div>{children}</section>}
function Footer({text}){return <footer className="footer"><span>{text}</span><span>05.09.2026 · 10:42:37</span></footer>}

function StationHome({go}){return <div className="screen industrial"><TopBar title="ЯДРО · ПОЛНАЯ ВЕРСИЯ" subtitle="Станция 01 · версия 0.3" onEngineering={()=>go("engineering")}/><main className="workspace station-layout"><div className="station-intro"><div><span className="eyebrow">ГЛАВНОЕ ОКНО ЯДРА</span><h1>Измерительные системы</h1><p>Станция запускает надстройки и распределяет оборудование между отдельными сеансами.</p></div><Button primary onClick={()=>go("ktma")}><RocketLaunch/> ОТКРЫТЬ КТМА</Button></div><Panel title="ЗАГРУЖЕННЫЕ НАДСТРОЙКИ" badge={<Status>3 ГОТОВЫ</Status>}><div className="overlay-list"><button className="overlay selected" onClick={()=>go("ktma")}><b>КТМА</b><span>стендовые проверки и производственные измерения</span><Status>ЗАГРУЖЕНА</Status><ArrowRight/></button><button className="overlay"><b>ЛАБ</b><span>универсальные приборные измерения</span><Status>ГОТОВА</Status><ArrowRight/></button><button className="overlay"><b>ДИАГ</b><span>сервисная диагностика оборудования</span><Status tone="warn">ОГРАНИЧЕНА</Status><ArrowRight/></button></div></Panel><div className="station-grid"><Panel title="АКТИВНЫЕ СЕАНСЫ" badge={<span className="counter">02 ОКНА</span>}><SessionRows/></Panel><Panel title="РЕСУРСЫ СТАНЦИИ" badge={<Status>7 / 7</Status>}><ResourceRows/></Panel></div></main><Footer text="Ядро управляет окнами и ресурсами · предметная логика находится в надстройках"/></div>}
function SessionRows(){return <div className="rows"><div className="data-row selected"><b>УБСИ-01</b><span>КТМА · ЯЛК-96 · 57 / 80</span><Status>ВЫПОЛНЯЕТСЯ</Status></div><div className="data-row"><b>ЯЧЕЙКА-02</b><span>КТМА · входное измерение</span><Status tone="warn">ОЖИДАЕТ</Status></div></div>}
function ResourceRows(){return <div className="rows compact">{[["Адаптер УБСИ","УБСИ-01"],["ИСД","УБСИ-01"],["В7-78/1","УБСИ-01"],["Р4831","свободен"]].map(([a,b])=><div className="data-row" key={a}><b>{a}</b><span>{b}</span><Status>{b==="свободен"?"ГОТОВ":"ЗАНЯТ"}</Status></div>)}</div>}

function KtmaHome({go}){return <div className="screen industrial"><TopBar title="КТМА · ПОЛНЫЙ КОНТУР" subtitle="производственная надстройка" onBack={()=>go("station")} onEngineering={()=>go("engineering")}/><main className="workspace ktma-layout"><aside className="module-rail"><div className="rail-head"><span className="eyebrow">КТМА</span><b>НАПРАВЛЕНИЯ</b></div>{modules.map(([id,t,s,Icon])=><button onClick={()=>go(id)} key={id}><Icon/><span><b>{t}</b><small>{s}</small></span><ArrowRight/></button>)}<div className="rail-head tools"><span className="eyebrow">ИНСТРУМЕНТЫ</span></div><button onClick={()=>go("scenario-simple")}><PuzzlePiece/><span><b>Сценарий</b><small>визуальный конструктор</small></span><ArrowRight/></button><button onClick={()=>go("database")}><Database/><span><b>БД и отчёты</b><small>история производства</small></span><ArrowRight/></button></aside><section className="ktma-main"><div className="station-intro"><div><span className="eyebrow">ДИСПЕТЧЕРИЗАЦИЯ ПРОИЗВОДСТВА</span><h1>Что требуется измерить</h1><p>Очередь изделий, промежуточных операций и незавершённых отчётов.</p></div><Button primary onClick={()=>go("ubsi")}><Play/> ОТКРЫТЬ СЕАНС</Button></div><Panel title="ПРОИЗВОДСТВЕННАЯ ОЧЕРЕДЬ" badge={<span className="counter">05.09.2026</span>}><ProductionTable/></Panel><div className="module-grid">{modules.map(([id,t,s,Icon],i)=><button className={i===0?"module-tile selected":"module-tile"} onClick={()=>go(id)} key={id}><Icon/><b>{t}</b><span>{s}</span><strong>{i===0?"3 В РАБОТЕ":i===3?"7 ОЖИДАЮТ":"ГОТОВО"}</strong></button>)}</div></section></main><Footer text="КТМА · локальная БД · синхронизация предприятия не настроена"/></div>}
function ProductionTable(){const rows=[["УБСИ-468157-009","Разбор","ЯЛК-96","УБСИ","В РАБОТЕ","ok"],["БСИ-468157-042","Входной","БСИ","БСИ","ОЖИДАЕТ","warn"],["ЯЛК-96 № 96-00427","До сборки","Адресная","Ячейка","ТРЕБУЕТСЯ","warn"],["АКИП-1160/6 №010","Сборка","Питание 24 В","Промежуточное","ГОТОВО","ok"]];return <table className="table"><thead><tr><th>ИЗДЕЛИЕ / ЯЧЕЙКА</th><th>ЭТАП</th><th>СЛЕДУЮЩЕЕ ДЕЙСТВИЕ</th><th>КОНТУР</th><th>СОСТОЯНИЕ</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td><b>{r[0]}</b></td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td><Status tone={r[5]}>{r[4]}</Status></td></tr>)}</tbody></table>}

function UbsiHub({go}){return <div className="screen industrial"><TopBar title="КТМА · УБСИ" subtitle="выбор испытания" onBack={()=>go("ktma")}/><main className="workspace"><div className="station-intro"><div><span className="eyebrow">ИСПЫТАТЕЛЬНЫЙ КОНТУР</span><h1>УБСИ · электрические проверки</h1><p>Выберите изделие и маршрут. Технические адреса скрыты до расширенного режима.</p></div></div><div className="choice-grid"><button className="choice selected" onClick={()=>go("test",0)}><Waveform/><b>ЯЛК-96</b><span>80 каналов · 0 / 3,1 / 6,2 В</span><strong>ОТКРЫТЬ</strong></button><button className="choice" onClick={()=>go("test",4)}><Pulse/><b>ЯТП</b><span>30 каналов · 0 / 120 / 240 Ω</span><strong>ОТКРЫТЬ</strong></button><button className="choice" onClick={()=>go("test",0)}><FlowArrow/><b>ЯЛК-96 + ЯТП</b><span>последовательный полный маршрут</span><strong>ОТКРЫТЬ</strong></button></div><Panel title="НАЗНАЧЕННЫЕ ИЗДЕЛИЯ"><ProductionTable/></Panel></main><Footer text="УБСИ · только ЯЛК-96 и ЯТП в текущей методике"/></div>}
function StageRail({current,setCurrent}){return <div className="stage-rail">{stages.map((s,i)=><button key={s[0]} className={`${i===current?"current":""} ${i<current?"done":""}`} onClick={()=>setCurrent(i)}><span>{i<current?<CheckCircle weight="fill"/>:s[0]}</span><b>{s[1]}</b><small>{s[2]}</small></button>)}</div>}
function TestFlow({go,initialStep=0}){const [step,setStep]=useState(initialStep);const [dialog,setDialog]=useState(false);const next=()=>setStep(v=>Math.min(7,v+1));const prev=()=>setStep(v=>Math.max(0,v-1));return <div className="screen industrial test-screen"><TopBar title="КТМА · УБСИ · СЕАНС 01" subtitle="УБСИ-468157-009 · разбор" onBack={()=>go("ubsi")}/><main className="test-workspace"><div className="test-head"><div><span className="eyebrow">ПОЛНЫЙ МАРШРУТ</span><h1>{stages[step][1]}</h1><p>Шаг {step+1} из 8 · методика ТУ 5.6 · сценарий 1.3</p></div><Status tone={step===5?"warn":"ok"}>{step===5?"ДЕЙСТВИЕ ОПЕРАТОРА":"ДАННЫЕ СВЕЖИЕ"}</Status></div><StageRail current={step} setCurrent={setStep}/><div className="test-body"><StageContent step={step} openDialog={()=>setDialog(true)} go={go}/><Panel title="ХОД ПРОЦЕДУРЫ" className="side-progress"><div className="progress-number">{Math.round((step+1)/8*100)}%</div><div className="progress-line"><i style={{width:`${(step+1)/8*100}%`}}/></div><dl><dt>Изделие</dt><dd>УБСИ-468157-009</dd><dt>Стенд</dt><dd>Стенд 01</dd><dt>Источник</dt><dd>{step<4?"адаптер + В7":"ЯТП + Р4831"}</dd><dt>Ошибки</dt><dd className="ok-text">0</dd></dl></Panel></div></main><div className="commandbar"><div><small>ИТОГ</small><b>{step===7?"НОРМА":"ВЫПОЛНЯЕТСЯ"}</b></div><Button onClick={prev} disabled={step===0}><ArrowLeft/> НАЗАД</Button><Button danger><ShieldCheck/> БЕЗОПАСНО ОСТАНОВИТЬ</Button><Button primary onClick={next} disabled={step===7}>СЛЕДУЮЩИЙ ШАГ <ArrowRight/></Button></div>{dialog&&<ResistanceDialog close={()=>setDialog(false)} confirm={()=>{setDialog(false);next()}}/>}</div>}

function StageContent({step,openDialog,go}){if(step===0)return <Panel title="НАЗНАЧЕНИЕ И МЕТОДИКА" badge={<Status>ПОДТВЕРЖДЕНО</Status>}><div className="form-grid"><Field label="ЗАВОДСКОЙ НОМЕР" value="УБСИ-468157-009"/><Field label="СОСТАВ" value="ЯЛК-96 № 96-00427 · ЯТП № ТП-00184"/><Field label="ПРОЦЕДУРА" value="ЯЛК-96 + ЯТП"/><Field label="ЭТАП ИЗДЕЛИЯ" value="Разбор"/></div><Notice>Привязка состава подтверждена. Результат может быть приёмочным.</Notice></Panel>;if(step===1)return <Panel title="ГОТОВНОСТЬ ОБОРУДОВАНИЯ" badge={<Status>5 / 5</Status>}><Checklist items={["Адаптер УБСИ · поток доступен","ИСД · управление доступно","В7-78/1 · эталон подключён","Р4831 · ручная операция подтверждена","Безопасное состояние выходов"]}/></Panel>;if(step===2)return <Panel title="КАЛИБРОВКА ЯЛК-96" badge={<Status>97 / 99</Status>}><div className="calibration"><Measure label="АДРЕС 97" value="0,512 В" sub="нулевая точка"/><div className="cal-line"><i/></div><Measure label="АДРЕС 99" value="5,986 В" sub="шкала"/></div><Notice>Для расчёта используются адреса 97 и 99. Адрес 98 не заменяет 99.</Notice></Panel>;if(step===3)return <Panel title="КАНАЛЫ ЯЛК-96 · АДРЕС 57" badge={<Status>57 / 80</Status>}><Plot/><MeasurementTable/></Panel>;if(step===4)return <Panel title="ЯТП · ТОЧКА 0 Ω" badge={<Status>30 / 30</Status>}><ResistanceSummary target="0 Ω"/><ChannelTable/></Panel>;if(step===5)return <Panel title="ЯТП · ТОЧКА 120 Ω" badge={<Status tone="warn">ТРЕБУЕТСЯ</Status>}><Notice warn>Физически установите 120 Ω на магазине Р4831, затем подтвердите фактическое значение.</Notice><div className="manual-action"><Measure label="ЦЕЛЕВОЕ СОПРОТИВЛЕНИЕ" value="120 Ω" sub="магазин подключён к общему X123"/><Button primary onClick={openDialog}><Gear/> ОТКРЫТЬ ДИАЛОГ Р4831</Button></div><ChannelTable/></Panel>;if(step===6)return <Panel title="ЯТП · ТОЧКА 240 Ω" badge={<Status>30 / 30</Status>}><ResistanceSummary target="240 Ω"/><ChannelTable/></Panel>;return <Panel title="ИТОГ И БЕЗОПАСНЫЙ СБРОС" badge={<Status>НОРМА</Status>}><div className="verdict"><CheckCircle weight="fill"/><div><span>ПРИЁМОЧНЫЙ ИТОГ</span><h2>УБСИ СООТВЕТСТВУЕТ ТУ 5.6</h2><p>ЯЛК-96: 80/80 · ЯТП: 30/30 по трём точкам · оборудование сброшено безопасно</p></div></div><div className="actions-row"><Button onClick={()=>go("reports")}><FileText/> ОТКРЫТЬ ПРОТОКОЛ</Button><Button primary onClick={()=>go("ktma")}><CheckCircle/> ЗАВЕРШИТЬ СЕАНС</Button></div></Panel>}
function Field({label,value}){return <label className="field"><span>{label}</span><input value={value} readOnly/></label>}
function Notice({children,warn}){return <div className={`notice ${warn?"warn":""}`}>{warn?<Warning/>:<ShieldCheck/>}<span>{children}</span></div>}
function Checklist({items}){return <div className="checklist">{items.map(x=><div key={x}><CheckCircle weight="fill"/><span>{x}</span><b>НОРМА</b></div>)}</div>}
function Measure({label,value,sub}){return <div className="measure"><span>{label}</span><b>{value}</b><small>{sub}</small></div>}
function Plot(){return <div className="plot"><div className="plot-bars">{[32,44,41,58,54,70,67,82,78,88,92,86,95].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><span>16 свежих отсчётов · В7 и ЯЛК</span></div>}
function MeasurementTable(){return <table className="table"><thead><tr><th>ТОЧКА</th><th>ЗАДАНО</th><th>В7</th><th>ЯЛК</th><th>ПОГРЕШНОСТЬ</th><th>ИТОГ</th></tr></thead><tbody>{[["0 В","0,000","0,002","0,001","+0,03 %"],["3,1 В","3,100","3,107","3,105","−0,032 %"],["6,2 В","6,200","6,145","6,148","+0,21 %"]].map(r=><tr key={r[0]}>{r.map(x=><td key={x}>{x}</td>)}<td><Status>НОРМА</Status></td></tr>)}</tbody></table>}
function ResistanceSummary({target}){return <div className="summary-metrics"><Measure label="ТОЧКА" value={target} sub="Р4831 подтверждён"/><Measure label="КАНАЛЫ" value="30 / 30" sub="свежий кадр"/><Measure label="МАКС. ОТКЛОНЕНИЕ" value="0,28 %" sub="допуск ±0,50 %"/></div>}
function ChannelTable(){return <table className="table"><thead><tr><th>КАНАЛ</th><th>ИЗМЕРЕНО</th><th>ОТКЛОНЕНИЕ</th><th>ДОПУСК</th><th>ИТОГ</th></tr></thead><tbody>{[1,2,3,4].map(n=><tr key={n}><td>{String(n).padStart(2,"0")}</td><td>120,{28+n} Ω</td><td>+0,{22+n} %</td><td>±0,50 %</td><td><Status>НОРМА</Status></td></tr>)}</tbody></table>}
function ResistanceDialog({close,confirm}){const [checked,setChecked]=useState(false);return <div className="modal"><div className="dialog"><div className="panel-title"><div><span className="eyebrow">РУЧНАЯ ОПЕРАЦИЯ · Р4831</span><h2>Точка ЯТП · канал 01 / 30</h2></div><button onClick={close} className="icon-close"><Stop/></button></div><Measure label="УСТАНОВИТЬ НА МАГАЗИНЕ" value="120 Ω" sub="общий разъём X123"/><div className="form-grid"><Field label="ФАКТИЧЕСКОЕ ЗНАЧЕНИЕ, Ω" value="120,34"/><Field label="ДОПУСК" value="±0,50 %"/></div><label className="confirm"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/> Р4831 физически установлен на заданное сопротивление</label><div className="audit-line"><span>Оператор: <b>Иванов И.И.</b></span><span>05.09.2026 · 10:21:14</span></div><div className="actions-row"><Button onClick={close}>ОТМЕНА</Button><Button primary disabled={!checked} onClick={confirm}>ПОДТВЕРДИТЬ ТОЧКУ</Button></div></div></div>}

function ModuleScreen({kind,go}){const config={bsi:["БСИ","Блоки, состав и измеряемые параметры"],cells:["Отдельные ячейки","Испытание вне сборки по типу и заводскому номеру"],intermediate:["Промежуточные измерения","Оцифровка операций, которые сейчас выполняются вручную"]}[kind];return <div className="screen industrial"><TopBar title={`КТМА · ${config[0]}`} subtitle="производственный контур" onBack={()=>go("ktma")}/><main className="workspace"><div className="station-intro"><div><span className="eyebrow">НАПРАВЛЕНИЕ КТМА</span><h1>{config[0]}</h1><p>{config[1]}</p></div><Button primary><Play/> СОЗДАТЬ СЕАНС</Button></div><div className="station-grid"><Panel title="ДОСТУПНЫЕ ПРОЦЕДУРЫ"><ProcedureRows kind={kind}/></Panel><Panel title="НАЗНАЧЕНО ПРОИЗВОДСТВУ"><ProductionTable/></Panel></div></main><Footer text={`${config[0]} · отдельное окно сеанса · общий механизм отчётности`}/></div>}
function ProcedureRows({kind}){const data=kind==="bsi"?["Входной контроль блока","Проверка параметров в сборе","Финальная ведомость"]:kind==="cells"?["ЯЛК-96 вне сборки","ЯТП вне сборки","Адресная диагностика"]:["Питание 24 В","Сопротивление изоляции","Температура после выдержки","Комментарий и внешний протокол"];return <div className="rows">{data.map((x,i)=><div className="data-row" key={x}><b>{String(i+1).padStart(2,"0")}</b><span>{x}</span><Status tone={i===data.length-1?"warn":"ok"}>{i===data.length-1?"РУЧНАЯ":"ГОТОВО"}</Status></div>)}</div>}

function ScenarioSimple({go}){return <div className="screen industrial"><TopBar title="КТМА · ВИЗУАЛЬНЫЙ СЦЕНАРИЙ" subtitle="упрощённый конструктор" onBack={()=>go("ktma")}/><main className="workspace"><div className="station-intro"><div><span className="eyebrow">ДОСТУПНО В ИСПЫТАТЕЛЬНОМ РЕЖИМЕ</span><h1>Собрать маршрут как последовательность блоков</h1><p>Без YAML и технических адресов. Каждый блок имеет понятное условие и результат.</p></div><Button onClick={()=>go("scenario-full")}><Wrench/> ПОЛНЫЙ РЕДАКТОР</Button></div><div className="puzzle-workspace"><aside className="puzzle-palette"><b>БЛОКИ</b>{["Подготовка стенда","Измерение ЯЛК","Ручная точка ЯТП","Условие допуска","Сформировать отчёт"].map(x=><button key={x}><PuzzlePiece/>{x}</button>)}</aside><Panel title="МАРШРУТ · УБСИ ПОЛНЫЙ"><div className="flow-canvas">{["Готовность","Калибровка 97/99","ЯЛК · 80 каналов","ЯТП · 0 Ω","ЯТП · 120 Ω","ЯТП · 240 Ω","Итог"].map((x,i)=><div className={i===4?"flow-node attention":"flow-node"} key={x}><span>{String(i+1).padStart(2,"0")}</span><b>{x}</b>{i<6&&<ArrowRight/>}</div>)}</div></Panel></div></main><Footer text="Упрощённый сценарий публикуется только после инженерной проверки"/></div>}

function Engineering({go}){return <div className="screen engineering"><TopBar title="ИНЖЕНЕРНЫЙ ПУЛЬТ СТАНЦИИ" subtitle="F12 · полный доступ" mode="engineering" onEngineering={()=>go("station")}/><main className="engineering-layout"><aside className="engine-nav"><b>СТАНЦИЯ</b>{[["ktma","Надстройки",SquaresFour],["scenario-full","Редактор сценария",FlowArrow],["address","Поадресная проверка",ListMagnifyingGlass],["database","База данных",Database],["reports","Автоматизация отчётов",FileText]].map(([id,t,Icon])=><button onClick={()=>go(id)} key={id}><Icon/>{t}</button>)}</aside><section className="engine-main"><div className="station-intro"><div><span className="eyebrow">ПОЛНАЯ ВЕРСИЯ</span><h1>Сеансы, структура объекта и оборудование</h1></div></div><Panel title="АКТИВНЫЕ СЕАНСЫ"><ProductionTable/></Panel><div className="engineering-columns"><Panel title="СТРУКТУРА ОБЪЕКТА"><Tree/></Panel><Panel title="СХЕМА ВЫБРАННОЙ ЯЧЕЙКИ"><Schematic/></Panel><Panel title="СОСТОЯНИЕ СТАНЦИИ"><Checklist items={["Измерительные модули 12 / 12","Каналы коммутации 240 / 240","Терминальные адаптеры 4 / 4","Локальная БД активна"]}/></Panel></div></section></main><Footer text="Инженерный пульт · технические адреса и диагностика доступны"/></div>}
function Tree(){return <div className="tree"><b>УБСИ-468157-009</b><span>Блоки</span><em>Блок коммутации</em><span>Ячейки</span><em className="selected">ЯЛК-96 № 96-00427</em><em>ЯТП № ТП-00184</em></div>}
function Schematic(){return <div className="schematic"><div>ВХОД 01</div><ArrowRight/><div className="selected">ЯЛК-96<br/>АДРЕС 57</div><ArrowRight/><div>ВЫХОД В7</div></div>}

function ToolScreen({type,go}){const c={"scenario-full":["Редактор сценария","YAML, граф шагов, diff и публикация",FlowArrow],address:["Поадресная проверка","Расширенная диагностика каналов и регистров",MagnifyingGlass],database:["База данных производства","Объекты, блоки, ячейки, запуски и переносы",Database],reports:["Автоматизация отчётности","Протокол запуска, ведомость и накопительный паспорт",FileText]}[type];const Icon=c[2];return <div className="screen engineering"><TopBar title={`КТМА · ${c[0]}`} subtitle="инженерный инструмент" mode="engineering" onBack={()=>go("engineering")}/><main className="workspace"><div className="station-intro"><div><span className="eyebrow">ИНЖЕНЕРНЫЙ РЕЖИМ</span><h1><Icon/> {c[0]}</h1><p>{c[1]}</p></div><Button primary>СОХРАНИТЬ ЧЕРНОВИК</Button></div>{type==="database"?<DatabaseView/>:type==="address"?<AddressView/>:type==="reports"?<ReportView/>:<FullEditor/>}</main><Footer text={`${c[0]} · изменения фиксируются в журнале`}/></div>}
function DatabaseView(){return <div className="db-layout"><Panel title="ПОИСК"><div className="form-grid"><Field label="ЗАВОДСКОЙ НОМЕР" value="БСИ-468157-042"/><Field label="ЭТАП" value="Все этапы"/></div><div className="db-results">{["БСИ-468157-042","УБСИ-468157-009","ЯЛК-96 № 96-00427"].map((x,i)=><button className={i===0?"selected":""} key={x}><b>{x}</b><small>{i===0?"изделие · разбор":i===1?"ячейка · установлена":"узел · проверен"}</small></button>)}</div></Panel><Panel title="КАРТОЧКА ИЗДЕЛИЯ" badge={<Status>АКТИВНО</Status>}><div className="passport"><h2>БСИ-468157-042</h2><p>Текущий этап: <b>Разбор</b></p><h3>СОСТАВ</h3><Checklist items={["УБСИ-468157-009 · установлена","ЯЛК-96 № 96-00427 · проверена","ЯТП № ТП-00184 · проверена"]}/><h3>ИСТОРИЯ</h3><div className="timeline"><span>05.09 · ЯЛК-96 · НОРМА</span><span>05.09 · ЯТП · НЕПОЛНАЯ</span><span>02.09 · перенос ячейки · Петров П.П.</span></div></div></Panel></div>}
function AddressView(){return <div className="station-grid"><Panel title="АДРЕСА ЯЛК-96" badge={<Status>ПОТОК АКТИВЕН</Status>}><table className="table"><thead><tr><th>АДРЕС</th><th>RAW</th><th>АНАЛОГ</th><th>СИГНАЛ</th><th>СОСТОЯНИЕ</th></tr></thead><tbody>{[1,32,57,74,97,99].map(n=><tr key={n}><td>{n}</td><td>0x{(32700+n).toString(16).toUpperCase()}</td><td>{n===97?"−0,512":n===99?"0,512":"0,002"} В</td><td>0,00 % FS</td><td><Status>НОРМА</Status></td></tr>)}</tbody></table></Panel><Panel title="ДЕЙСТВИЯ"><Checklist items={["Чтение без воздействия","Калибровочные адреса 97 / 99","Трассировка источника","История и статистика"]}/><Notice warn>Команды воздействия требуют административного режима и свободного оборудования.</Notice></Panel></div>}
function ReportView(){return <div className="report-layout"><Panel title="ЗАПУСКИ"><ProductionTable/></Panel><Panel title="ПРЕДПРОСМОТР"><div className="report-sheet"><span>МИЛТЕХ СТАНЦИЯ · КТМА</span><h2>ПРОТОКОЛ ПРОВЕРКИ УБСИ</h2><hr/><p>Изделие: <b>УБСИ-468157-009</b></p><p>ЯЛК-96: <b className="ok-text">НОРМА</b></p><p>ЯТП: <b className="warn-text">НЕПОЛНАЯ</b></p><p>Сценарий 1.3 · каталог 2.1 · Стенд 01</p></div></Panel></div>}
function FullEditor(){return <div className="editor-layout"><Panel title="СХЕМА ШАГОВ"><div className="flow-canvas vertical">{["Подключение","ROKT init","Калибровка 97/99","Цикл 80 каналов","Условие допуска","Безопасный сброс"].map((x,i)=><div className="flow-node" key={x}><span>{i+1}</span><b>{x}</b></div>)}</div></Panel><Panel title="СВОЙСТВА ШАГА"><div className="form-grid"><Field label="ТИП" value="Измерение"/><Field label="ИСТОЧНИК" value="ЯЛК-96"/><Field label="ПОВТОРЫ" value="16 свежих отсчётов"/><Field label="ДОПУСК" value="±0,50 %"/></div><Notice warn>Опубликованная версия заблокирована. Изменения создадут черновик 1.4.</Notice></Panel></div>}

export function App(){const [route,setRoute]=useState("station");const [testInitial,setTestInitial]=useState(0);const go=(r,step=0)=>{setTestInitial(step);setRoute(r)};if(route==="station")return <StationHome go={go}/>;if(route==="ktma")return <KtmaHome go={go}/>;if(route==="ubsi")return <UbsiHub go={go}/>;if(route==="test")return <TestFlow key={testInitial} go={go} initialStep={testInitial}/>;if(["bsi","cells","intermediate"].includes(route))return <ModuleScreen kind={route} go={go}/>;if(route==="scenario-simple")return <ScenarioSimple go={go}/>;if(route==="engineering")return <Engineering go={go}/>;return <ToolScreen type={route} go={go}/>}
