param(
    [string]$AddressDirectory = (Join-Path $PSScriptRoot '..\orbita\config\address')
)

$ErrorActionPreference = 'Stop'
$addressRoot = [IO.Path]::GetFullPath($AddressDirectory)
if (-not (Test-Path -LiteralPath $addressRoot -PathType Container)) {
    throw "Address directory not found: $addressRoot"
}

$cp1251 = [Text.Encoding]::GetEncoding(1251)
$latin = @{
    ([char]0x0410) = 'A'; ([char]0x0412) = 'B'; ([char]0x0415) = 'E'
    ([char]0x041a) = 'K'; ([char]0x041c) = 'M'; ([char]0x041d) = 'H'
    ([char]0x041e) = 'O'; ([char]0x041f) = 'P'; ([char]0x0420) = 'P'
    ([char]0x0421) = 'C'; ([char]0x0422) = 'T'; ([char]0x0425) = 'X'
}

function RussianName([int[]]$Chars, [string]$Suffix = '.txt') {
    return (([string]::new([char[]]$Chars)) + $Suffix)
}

function Read-NormalizedAddresses([string]$Name) {
    $path = Join-Path $addressRoot $Name
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Source address file not found: $path"
    }
    $text = $cp1251.GetString([IO.File]::ReadAllBytes($path))
    foreach ($line in $text -split "`r?`n") {
        $address = $line.Trim()
        if (-not $address) { continue }
        foreach ($character in $latin.Keys) {
            $address = $address.Replace([string]$character, $latin[$character])
        }
        $address = $address.ToUpperInvariant()
        if ($address -notmatch '^M16P?[12][A-Z0-9]+T(01|05|11|21|22|23|24|25)(P\d{2})?$') {
            throw "Unexpected Orbita address in ${Name}: $address"
        }
        $address
    }
}

$slowName = RussianName @(0x041c,0x0435,0x0434,0x043b,0x0435,0x043d,0x043d,0x044b,0x0435,0x0020,0x0423,0x041b,0x041a)
$fastName = RussianName @(0x0411,0x044b,0x0441,0x0442,0x0440,0x044b,0x0435)
$contactName = RussianName @(0x041a,0x043e,0x043d,0x0442,0x0430,0x043a,0x0442,0x043d,0x044b,0x0435,0x0020,0x0423,0x041b,0x041a)

$groups = [ordered]@{
    slow = @($slowName, @(Read-NormalizedAddresses $slowName | Select-Object -Unique))
    fast = @($fastName, @(Read-NormalizedAddresses $fastName | Select-Object -Unique))
    contacts = @($contactName, @(Read-NormalizedAddresses $contactName | Select-Object -Unique))
}

$outputs = [ordered]@{
    'ulk_slow.txt' = @($groups.slow[1])
    'ulk_fast.txt' = @($groups.fast[1])
    'ulk_contacts.txt' = @($groups.contacts[1])
    'ulk_all.txt' = @($groups.slow[1] + $groups.fast[1] + $groups.contacts[1] | Select-Object -Unique)
}

foreach ($output in $outputs.GetEnumerator()) {
    [IO.File]::WriteAllLines((Join-Path $addressRoot $output.Key), [string[]]$output.Value, [Text.UTF8Encoding]::new($false))
}

$manifest = [Collections.Generic.List[string]]::new()
$manifest.Add('# Generated by scripts/consolidate_orbita_address_sets.ps1. Source files are not modified.')
$manifest.Add('group;source;address_count')
$manifest.Add(('slow;{0};{1}' -f $groups.slow[0], $groups.slow[1].Count))
$manifest.Add(('fast;{0};{1}' -f $groups.fast[0], $groups.fast[1].Count))
$manifest.Add(('contacts;{0};{1}' -f $groups.contacts[0], $groups.contacts[1].Count))
$manifest.Add(('all;ulk_all.txt;{0}' -f $outputs['ulk_all.txt'].Count))
[IO.File]::WriteAllLines((Join-Path $addressRoot 'ULK_ADDRESS_REGISTRY.csv'), [string[]]$manifest, [Text.UTF8Encoding]::new($false))

$outputs.GetEnumerator() | ForEach-Object {
    [pscustomobject]@{ File = $_.Key; Addresses = $_.Value.Count }
}
